### ISSUE TITLE
Census events with dtWF model

### ISSUE THREAD

**Issue by Arslan-Zaidi** [tskit-dev/msprime#1543]
Hello,

I am trying to add a census event in the recent past before my model switches from dtWF to Hudson but I'm running into the following error:

"_msprime.LibraryError: The simulation model supplied resulted in a parent node having a time value <= to its child. This can occur either as a result of multiple bottlenecks happening at the same time or because of numerical imprecision with very small population sizes."

It only happens if I try to call CensusEvent during the Wright-Fisher phase even though I am specifying time as an integer for the census event. Here is the demography I am simulating (sorry couldn't run DemographyDebugger as it doesn't work with model switches currently):

[{'type': 'census_event', 'time': 50.0}, 
{'type': 'migration_rate_change', 'time': 100, 'rate': 0.0, 'matrix_index': None}, 
{'type': 'mass_migration', 'time': 100, 'source': 0, 'dest': 5, 'proportion': 1.0}, 
{'type': 'mass_migration', 'time': 100, 'source': 1, 'dest': 5, 'proportion': 1.0}, 
{'type': 'mass_migration', 'time': 100, 'source': 2, 'dest': 5, 'proportion': 1.0}, 
{'type': 'mass_migration', 'time': 100, 'source': 3, 'dest': 5, 'proportion': 1.0}, 
{'type': 'mass_migration', 'time': 100, 'source': 4, 'dest': 5, 'proportion': 1.0}, 
{'type': 'simulation_model_change', 'time': 1000.0, 'model': 'hudson'}]

Population size = 1e4, length = 1e6, mutation_rate = 0, migration_rate = 0.001

Is this a bug or is there something I'm missing.

Thanks!

**Comment by jeromekelleher** [comment]
Hi Arslan, thanks for the bug report! Would you mind trying this out with the latest version of the code please (or paste the code in here)?

The development version has moved along way from 0.7.4 now, and is due to be released in a few weeks, so this bug may have been resolved already.

**Comment by Arslan-Zaidi** [comment]
Hi Jerome, Thanks for the quick response. I see. I'll try the development version to see if that fixes things. In the meanwhile, here's the code I'm using:

`
#number of demes
d = args.ndemes
#migration rate
m = args.migrate
#mutation rate
mu = args.mu
#recombination_rate
rho = args.rho
#length of chromosome
L = args.length
#diploid sample size within each deme
ss=args.ss
#Ne
N = args.npop
#time to panmixia
tmove = args.tmove
#outprefix
outpre = args.outpre

#generate migration matrix
mig_mat=np.full([d,d], m)
#set diagonal to 0
np.fill_diagonal(mig_mat, 0.0)

##### define function to simulate genotypes under a island migration model
def island(tmove = tmove, ss_each = 2*ss):
    #N is the population size for each deme
    #ss_each is the haploid sample size for each deme
    #l is the length of the chromosome
    #tmove is the number of generations past which all lineages are moved into one deme.
    sample_sizes = [ss_each] * d
    population_configurations = [
        msprime.PopulationConfiguration(sample_size = k) for k in sample_sizes]

    #define recombination map with a chrom of length L and an independently segregating piece at the end
    positions = [0, L-1, L, L+1]
    rates = [rho, 0.5, 0, 0]
    num_loci = positions[-1] // 100 # Discretize into 100bp chunks as recommended

    recombination_map = msprime.RecombinationMap(
            positions=positions, rates=rates, num_loci=num_loci)

    ### Demographic events
    #1. change migration rate among demes to be 0 at t=tmove
    demog = [msprime.MigrationRateChange(
        time = tmove,
        rate = 0.0)]

    #2. move all lineages to deme d+1 after t=tmove
    demog = demog + [msprime.MassMigration(
        time = tmove,
        source = i,
        destination = d - 1,
        proportion = 1.0) for i in range(d - 1)]

    #3. change model from dtWF to Hudson at t = 1000
    demog = demog + [msprime.SimulationModelChange(
        time = 1000,
        model = "hudson")]

    #add census event at 10 generations
    demog = [msprime.CensusEvent(time = 50)] + demog

    ts = msprime.simulate(
    population_configurations = population_configurations,
    Ne = N,
    migration_matrix = mig_mat,
    mutation_rate = mu,
    model = "dtwf"
    recombination_map = recombination_map,
    demographic_events = demog)

    return(ts)

print("simulating genotypes under demographic model")

#simulate!
ts = island(ss_each = 2*ss)

#convert to slim tree format
slim_ts = pyslim.annotate_defaults(ts, model_type = "WF", slim_generation = 1)

#dump tree
slim_ts.dump(outpre + ".trees")`

I'll keep you posted on any developments on my end, thanks.

**Comment by Arslan-Zaidi** [comment]
Hi Jerome, an update here. I tried to run my code with the dev version of msprime and still see the same error. There seems to be a problem with using census events with the dtwf model as switching to the hudson model fully resolves the issue.

**Comment by jeromekelleher** [comment]
Great, thanks @Arslan-Zaidi - I've tagged it into 1.0 release so should be resolved soon.

**Comment by jeromekelleher** [comment]
Turns out this is a consequence of the integer times in the DTWF model @Arslan-Zaidi - if you specify a census time of g, and a coalescence allows happens to occur at this time also it'll lead to a zero branch length error when the census nodes are added. The easy solution is to use a non-integer time (e.g. 50.5 in your case above).

#1627 documents this quirk.

**Comment by Arslan-Zaidi** [comment]
That fixed it. Thanks, and congratulations on the new release! Excited to work with it.
